// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ompqyjdrfnjdxqavslhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tcHF5amRyZm5qZHhxYXZzbGhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyODc0NjAsImV4cCI6MjA3NDg2MzQ2MH0.kukgcpv7nSgTtWvPjsRT_0mbhln6WGPqVJzNwzGNOi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Banner Types
type Banner = Database['public']['Tables']['ad_banners']['Row'];
type BannerInsert = Database['public']['Tables']['ad_banners']['Insert'];
type BannerUpdate = Database['public']['Tables']['ad_banners']['Update'];

// Helper function to generate a unique filename
const generateUniqueFileName = (file: File) => {
  const timestamp = new Date().getTime();
  const randomString = Math.random().toString(36).substring(2, 15);
  const extension = file.name.split('.').pop();
  return `${timestamp}-${randomString}.${extension}`;
};

// Banner Management Functions
export const bannerService = {
  // Upload banner image to storage and return URL
  async uploadBannerImage(file: File) {
    // Generate a unique filename
    const filename = generateUniqueFileName(file);
    const filePath = `banners/${filename}`;

    // Upload the file to the ad-banners bucket
    const { error: uploadError } = await supabase.storage
      .from('ad-banners')
      .upload(filePath, file, {
        cacheControl: '3600',
        upsert: false
      });

    if (uploadError) throw uploadError;

    // Get the public URL
    const { data: { publicUrl } } = supabase.storage
      .from('ad-banners')
      .getPublicUrl(filePath);

    return {
      url: publicUrl,
      path: filePath
    };
  },
  // Get active banners for the current user role
  async getActiveBanners(userRole?: string) {
    const { data, error } = await supabase.rpc('get_active_banners', { user_role: userRole });
    if (error) throw error;
    return data;
  },

  // Get all banners (admin only)
  async getAllBanners() {
    const { data, error } = await supabase
      .from('ad_banners')
      .select('*')
      .order('display_order', { ascending: true });
    
    if (error) throw error;
    return data;
  },

  // Get a single banner by ID
  async getBannerById(id: number) {
    const { data, error } = await supabase
      .from('ad_banners')
      .select('*')
      .eq('id', id)
      .single();
    
    if (error) throw error;
    return data;
  },

  // Create a new banner
  async createBanner(banner: BannerInsert) {
    const { data, error } = await supabase
      .from('ad_banners')
      .insert(banner)
      .select()
      .single();
    
    if (error) throw error;
    return data;
  },

  // Update an existing banner
  async updateBanner(id: number, updates: BannerUpdate) {
    const { data, error } = await supabase
      .from('ad_banners')
      .update(updates)
      .eq('id', id)
      .select()
      .single();
    
    if (error) throw error;
    return data;
  },

  // Delete a banner
  async deleteBanner(id: number) {
    // First get the banner to get its image path
    const { data: banner, error: fetchError } = await supabase
      .from('ad_banners')
      .select('image_path')
      .eq('id', id)
      .single();
    
    if (fetchError) throw fetchError;

    // Delete the image from storage if it exists
    if (banner?.image_path) {
      const { error: storageError } = await supabase.storage
        .from('ad-banners')
        .remove([banner.image_path]);
      
      if (storageError) throw storageError;
    }

    // Delete the banner record
    const { error } = await supabase
      .from('ad_banners')
      .delete()
      .eq('id', id);
    
    if (error) throw error;
  },

  // Update banner display order
  async updateBannerOrder(id: number, newOrder: number) {
    const { error } = await supabase
      .from('ad_banners')
      .update({ display_order: newOrder })
      .eq('id', id);
    
    if (error) throw error;
  },

  // Increment banner view count
  async incrementViewCount(id: number) {
    const { error } = await supabase
      .from('ad_banners')
      .update({ view_count: supabase.rpc('increment') })
      .eq('id', id);
    
    if (error) throw error;
  },

  // Increment banner click count
  async incrementClickCount(id: number) {
    const { error } = await supabase
      .from('ad_banners')
      .update({ click_count: supabase.rpc('increment') })
      .eq('id', id);
    
    if (error) throw error;
  },

  // Toggle banner active status
  async toggleBannerStatus(id: number, isActive: boolean) {
    const { error } = await supabase
      .from('ad_banners')
      .update({ is_active: isActive })
      .eq('id', id);
    
    if (error) throw error;
  }
};