// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use the ad_banners type from the database
type BannerRow = {
  id: number;
  title: string;
  description: string | null;
  image_url: string;
  image_path: string | null;
  storage_bucket: string;
  link_url: string | null;
  link_type: 'external' | 'internal' | 'none';
  action_data: any;
  display_order: number;
  is_active: boolean;
  start_date: string | null;
  end_date: string | null;
  target_roles: string[] | null;
  view_count: number;
  click_count: number;
  created_at: string;
  updated_at: string;
  created_by: number | null;
};

type BannerInsert = Omit<BannerRow, 'id' | 'created_at' | 'updated_at' | 'view_count' | 'click_count'>;

const SUPABASE_URL = "https://ompqyjdrfnjdxqavslhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tcHF5amRyZm5qZHhxYXZzbGhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyODc0NjAsImV4cCI6MjA3NDg2MzQ2MH0.kukgcpv7nSgTtWvPjsRT_0mbhln6WGPqVJzNwzGNOi8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});


// Helper function to generate a unique filename
const generateUniqueFileName = (file: File) => {
  const timestamp = new Date().getTime();
  const randomString = Math.random().toString(36).substring(2, 15);
  const extension = file.name.split('.').pop();
  return `${timestamp}-${randomString}.${extension}`;
};

// Helper function to get the current user ID
const getCurrentUserId = async () => {
  const { data: { session }, error } = await supabase.auth.getSession();
  if (error) throw error;
  if (!session?.user) throw new Error('User must be authenticated');
  return session.user.id;
};

// Helper function to check if user is admin
const isUserAdmin = async () => {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return false;
  
  const { data, error } = await supabase
    .from('profiles')
    .select('role')
    .eq('id', user.id)
    .single();
  
  if (error) return false;
  if (!data) return false;
  return data.role === 'admin';
};

// Banner Management Functions
export const bannerService = {
  // Upload banner image to storage and return URL
  async uploadBannerImage(file: File) {
    const { storageService } = await import('./storage');
    
    const result = await storageService.uploadFile(file, {
      bucket: 'ad-banners',
      prefix: 'ad_banners',     // Ensure files go into ad_banners folder
      useYearMonth: true,      // Organize by year/month subfolders
      maxSizeMB: 5,
      allowedTypes: ['image/jpeg', 'image/png', 'image/webp'],
      cacheControl: '3600'
    });

    return {
      url: result.url,
      path: result.path,
      metadata: result.metadata
    };
  },
  // Get active banners for the current user role
  async getActiveBanners(userRole?: string) {
    const { data, error } = await supabase
      .from('ad_banners')
      .select('*')
      .eq('is_active', true)
      .order('display_order', { ascending: true });
    
    if (error) throw error;
    return data as BannerRow[];
  },

  // Get all banners (admin only)
  async getAllBanners() {
    const { data, error } = await supabase
      .from('ad_banners')
      .select('*')
      .order('display_order', { ascending: true });
    
    if (error) throw error;
    return data;
  },

  // Get a single banner by ID
  async getBannerById(id: number) {
    const { data, error } = await supabase
      .from('ad_banners')
      .select('*')
      .eq('id', id)
      .single();
    
    if (error) throw error;
    return data;
  },

  // Create a new banner
  async createBanner(banner: Partial<BannerInsert>) {
    const { data, error } = await supabase
      .from('ad_banners')
      .insert(banner as any)
      .select()
      .single();
    
    if (error) throw error;
    return data as BannerRow;
  },

  // Update an existing banner
  async updateBanner(id: number, updates: Partial<BannerRow>) {
    const { data, error } = await supabase
      .from('ad_banners')
      .update(updates as any)
      .eq('id', id)
      .select()
      .single();
    
    if (error) throw error;
    return data as BannerRow;
  },

  // Delete a banner
  async deleteBanner(id: number) {
    // First get the banner to get its image path
    const { data: banner, error: fetchError } = await supabase
      .from('ad_banners')
      .select('image_path')
      .eq('id', id)
      .single();
    
    if (fetchError) throw fetchError;

    // Delete the image from storage if it exists
    if (banner && banner.image_path) {
      const { storageService } = await import('./storage');
      await storageService.deleteFile(banner.image_path, 'ad-banners');
    }

    // Delete the banner record
    const { error } = await supabase
      .from('ad_banners')
      .delete()
      .eq('id', id);
    
    if (error) throw error;
  },

  // Update banner display order
  async updateBannerOrder(id: number, newOrder: number) {
    const { error } = await supabase
      .from('ad_banners')
      .update({ display_order: newOrder } as any)
      .eq('id', id);
    
    if (error) throw error;
  },

  // Increment banner view count
  async incrementViewCount(id: number) {
    // Get current count and increment
    const { data } = await supabase
      .from('ad_banners')
      .select('view_count')
      .eq('id', id)
      .single();
    
    if (data) {
      await supabase
        .from('ad_banners')
        .update({ view_count: (data.view_count || 0) + 1 } as any)
        .eq('id', id);
    }
  },

  // Increment banner click count
  async incrementClickCount(id: number) {
    // Get current count and increment
    const { data } = await supabase
      .from('ad_banners')
      .select('click_count')
      .eq('id', id)
      .single();
    
    if (data) {
      await supabase
        .from('ad_banners')
        .update({ click_count: (data.click_count || 0) + 1 } as any)
        .eq('id', id);
    }
  },

  // Toggle banner active status
  async toggleBannerStatus(id: number, isActive: boolean) {
    const { error } = await supabase
      .from('ad_banners')
      .update({ is_active: isActive } as any)
      .eq('id', id);
    
    if (error) throw error;
  }
};